# docker-compose.yml
version: '3.8'
services:
  shopify-automation:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports
    restart: unless-stopped
